version: '3'  

services:
  database:
    container_name: postgres-database
    image: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: users
    volumes:
      - ./init_users.sql:/docker-entrypoint-initdb.d/init.sql

#  auth:
#    container_name: auth-service
#    build: ./Authentication/
#    ports:
#      - "80:80"
#    restart: always
#  redis-cache: 
#    container_name: redis-server
#    image: redis
#    ports:
#      - "6379:6379"
#    environment:
#      REDIS_ARGS: "--requirepass 123 --user Daniel"

 
   
    

